spring:
  application:
    name: client
  datasource:
    url: jdbc:mysql://146.148.98.19/client?allowPublicKeyRetrieval=true&sslMode=DISABLED&useSSL=false&serverTimezone=UTC
    username: macc
    password: 1234qwer
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
