server:
  port: 8081
  servlet:
    context-path: /client

spring:
  application:
    name: client
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/client-db-mysql?allowPublicKeyRetrieval=true&sslMode=DISABLED&useSSL=false&serverTimezone=UTC
    username: microservices
    password: Microservices@123

springdoc:
  api-docs:
    path: /api-docs