kind: ConfigMap
apiVersion: v1
metadata:
  name: catalog
data:
  application.yaml: |-
    datasource:
      url: jdbc:mysql://localhost:3306/catalog?allowPublicKeyRetrieval=true&sslMode=DISABLED&useSSL=false&serverTimezone=UTC
      username: root
      password: root